title: 
  en: Video Player
  fr: Lecteur vidéo
description:
  en: A component plays a video.
  fr: Un composant lit une vidéo.
label:
  en: Video
  fr: Vidéo
assets:
  Screenshot.png:
    title: 
      en: A video player with controls.
      fr: Un lecteur vidéo avec des commandes.
input:
  type: video
  limit: one