title: 
  en: Image Gallery
  fr: Galerie d'images
description: 
  en: This is a section to showcase your images, plesantly arranged in a masonry layout that dynamically responds to your website.
  fr: Une section destinée à présenter vos images, disposées dans une disposition en maçonnerie qui s'adapte à votre site web.
label:
  en: Gallery
  fr: Galerie
assets:
  Screenshot.png:
    title: 
      en: Images in masonry layout with a leading title in light theme.
      fr: Images dans une disposition en maçonnerie avec un titre principal dans un thème clair.
  Gallery-Dark.png:
    title: 
      en: Four images in a row with a dark theme.
      fr: Quatre images d'affilée sur un thème foncé.
  Gallery-Light.png:
    title: 
      en: Four images in a row in a light theme.
      fr: Quatre images à la suite dans un thème léger.

elements:
  title:
    alignment: left,right,center
  media:
    type: image
    description: 
      en: The image to display.
      fr: L'image à afficher.

      