title: 
  en: Aside
  fr: Aside
label: 
  en: Aside
  fr: Aside
description: 
  en: A section displaying content aside from the main content, usually in one side of a two column layout.
  fr: Une section affichant du contenu à côté du contenu principal, généralement dans un côté d'une mise en page à deux colonnes.
assets:
  Screenshot.png:
    title: 
      en: A basic usage of showing the member's information.
      fr: Une utilisation de base de l'affichage des informations du membre.
input:
  type: any
  limit: one
  manualFormatting: true

elements:
  background:
    label:
      en: Profile Banner/Avatar
      fr: Bannière/Avatar de profil
    description: 
      en: The picture of the profile.
      fr: L'image du profil.
  title:
    description: 
      en: The title of the profile.
      fr: Le titre du profil.
  subtitle:
    description: 
      en: The subtitle of the profile.
      fr: Le sous-titre du profil.
  link:
    type: link
    description: 
      en: One or more links that attach to the profile.
      fr: Un ou plusieurs liens qui s'attachent au profil.