title:
  en: Hero
  fr: Héro
description:
  en: Hero banner
  fr: Bande héro
label:
  en: Hero
  fr: Héro

properties:
  presetAlign:
    label:
      en: Preset alignment
      fr: Alignement du préréglage
    type: string
    default: right
    enum:
      - label:
          en: Right
          fr: Droite
        value: right
  presetCol:
    label:
      en: Preset color
      fr: Couleur du préréglage
    type: string
    default: blue
    enum:
      - label:
          en: Blue
          fr: Bleu
        value: blue
  imageOne:
    label:
      en: Alignment of the first image
      fr: Alignement de la première image
    type: string
    default: left
    enum:
      - label:
          en: Bottom
          fr: Bas
        value: bottom
      - label:
          en: Bottom left
          fr: Bas gauche
        value: bottomLeft
      - label:
          en: Bottom right
          fr: Bas droit
        value: bottomRight
      - label:
          en: Left
          fr: Gauche
        value: left
      - label:
          en: Right
          fr: Droite
        value: right
      - label:
          en: Top
          fr: Haut
        value: top
      - label:
          en: Top left
          fr: Haut gauche
        value: topLeft
      - label:
          en: Top right
          fr: Haut droit
        value: topRight
  imageTwo:
    label:
      en: Alignment of the second image
      fr: Alignement de la seconde image
    type: string
    default: left
    enum:
      - label:
          en: Bottom
          fr: Bas
        value: bottom
      - label:
          en: Bottom left
          fr: Bas gauche
        value: bottomLeft
      - label:
          en: Bottom right
          fr: Bas droit
        value: bottomRight
      - label:
          en: Left
          fr: Gauche
        value: left
      - label:
          en: Right
          fr: Droite
        value: right
      - label:
          en: Top
          fr: Haut
        value: top
      - label:
          en: Top left
          fr: Haut gauche
        value: topLeft
      - label:
          en: Top right
          fr: Haut droit
        value: topRight