title: 
  en: Button
  fr: Bouton
description: 
  en: A simple button
  fr: Un bouton simple
label:
  en: Button
  fr: Bouton
# assets:
#   Screenshot.png:
#     title: 
#       en: Screenshot Description
#       fr: Description de la capture d'écran

elements:
  description:
    en: Add a link to the settings
    fr: Ajoutez un lien au paramètres

properties:
  type:
    label:
      en: type
      fr: type
    type: string
    default: primary
    enum:
      - label:
          en: Primary
          fr: Primaire
        value: primary
      - label:
          en: Secondary
          fr: Secondaire
        value: secondary
    description:
      en: Controls the type of button
      fr: Contrôle le type de bouton
  href:
    label:
      en: URL
      fr: URL
    type: string
    default: undefined
    description:
      en: The link where the button sends
      fr: Le lien où envoie le bouton