title: 
  en: Button
  fr: Button
description: 
  en: Button
  fr: Button
label:
  en: Button
  fr: Button
# assets:
#   Screenshot.png:
#     title: 
#       en: Screenshot Description
#       fr: Description de la capture d'écran

elements:
  title: