title:
  en: Code Block
  fr: Bloc de code
description:
  en: A fancy code block
  fr: Un bloc de code chic
label:
  en: Code Block
  fr: Bloc de code

properties:
  lang:
    label:
      en: language
      fr: langue
    type: string