title: 
  en: Map - Interactive
  fr: Carte - Interactive
description: 
  en: A full size map with pins and side details that ideally for embedding in a page.
  fr: Une carte en taille réelle avec des épingles et des détails latéraux, idéalement pour l'intégration dans une page.
label:
  en: Map - Interactive
  fr: Carte - Interactive
assets:
  Screenshot.png:
    title: 
      en: Map with pins and a list of locations on the left.
      fr: Carte avec des épingles et une liste d'emplacements sur la gauche.

elements:
  title:
  card:
    description: 
      en: One or more card with Address type.
      fr: Une ou plusieurs cartes avec le type Adresse.


properties:
  show_detail:
    label: 
      en: Show Details
      fr: Afficher les détails
    type: boolean
    default: true
    description: 
      en: Whether or not to show the details of the source profile of the location.
      fr: Si oui ou non afficher les détails du profil source de l'emplacement.
  zoom:
    label:
      en: Initial Zoom Level
      fr: Niveau de zoom initial
    type: string
    enum:
      - label:
          en: World view
          fr: Vue du monde
        value: "1"
      - label:
          en: Continent view
          fr: Vue du continent
        value: "5"
      - label:
          en: City view
          fr: Vue de la ville
        value: "10"
      - label:
          en: Street view
          fr: Vue de la rue
        value: "15"
      - label:
          en: Building view
          fr: Vue du bâtiment
        value: "20"
    default: "5"
    description: 
      en: The zoom level of the map.
      fr: Le niveau de zoom de la carte.