title: 
  en: Callout
  fr: Appel
description: 
  en: Callout
  fr: Appel
label:
  en: Callout
  fr: Appel
# assets:
#   Screenshot.png:
#     title: 
#       en: Screenshot Description
#       fr: Description de la capture d'écran

elements:
  title:
  text:

properties:
  type:
    label:
      en: type
      fr: type
    type: string
    default: info
    enum:
      - label:
          en: info
          fr: info
        value: info
      - label:
          en: warning
          fr: avertissement
        value: warning
    description:
      en: The type of callout
      fr: Le type d'appel