title: 
  en: Header
  fr: Entête
description: 
  en: The header of the page
  fr: L'entête de la page
label:
  en: Header
  fr: Entête
# assets:
#   Screenshot.png:
#     title: 
#       en: Screenshot Description
#       fr: Description de la capture d'écran
properties:
  mode:
    label:
      en: image mode
      fr: mode de l'image
    type: string
    default: "null"
    enum:
      - label:
          en: None
          fr: Aucune
        value: "null"
      - label:
          en: Image
          fr: Image
        value: image
      - label:
          en: Icon
          fr: Icône
        value: icon
  childrenMode:
    label:
      en: When to render children
      fr: Quand afficher sous-parties
    type: string
    default: home
    enum:
      - label:
          en: Never
          fr: Jamais
        value: Never
      - label:
          en: On home page
          fr: Sur la page d'accueil
        value: home
      - label:
          en: Always
          fr: Toujours
        value: always