title: 
  en: Header
  fr: Entête
description: 
  en: The header of the page
  fr: L'entête de la page
label:
  en: Header
  fr: Entête
# assets:
#   Screenshot.png:
#     title: 
#       en: Screenshot Description
#       fr: Description de la capture d'écran

elements:
  title:

properties:
  left_panel:
    label:
      en: Left panel
      fr: Panneau de gauche
    type: boolean
    default: true
    description:
      en: Whether or not to display the left panel
      fr: Affichage du panneau de gauche
  right_panel:
    label:
      en: Right panel
      fr: Panneau de droite
    type: boolean
    default: false
    description:
      en: Whether or not to display the right panel
      fr: Affichage du panneau de droite