title: 
  en: Header
  fr: Entête
description: 
  en: The header of the page
  fr: L'entête de la page
label:
  en: Header
  fr: Entête
# assets:
#   Screenshot.png:
#     title: 
#       en: Screenshot Description
#       fr: Description de la capture d'écran

elements:

properties:
  left_panel:
    label:
      en: Left panel
      fr: Panneau de gauche
    type: string
    default: true
    enum:
      - label:
          en: True
          fr: Vrai
        value: true
      - label:
          en: False
          fr: Faux
        value: false
    description:
      en: Whether or not to display the left panel
      fr: Affichage du panneau de gauche