title: 
  en: Header
  fr: Entête
description: 
  en: The header of the page
  fr: L'entête de la page
label:
  en: Header
  fr: Entête
# assets:
#   Screenshot.png:
#     title: 
#       en: Screenshot Description
#       fr: Description de la capture d'écran
